name: Intregar continuamente

on: [pull_request]

jobs:
  integracao:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - run: |
          pip install --upgrade pip # Aqui estou atualizando o atualizador de pacotes
          pip install -r requirements.txt # Instalando as biblioteas
          python3 app.py # Executando a aplicação
    
