name: Intregar continuamente

on: [push]

jobs:
  integracao:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do Código
      - uses: actions/checkout@v6

      - name: Configurar o Python
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Instalar as depedências da aplicação
        run: |
          pip install --upgrade pip # Aqui estou atualizando o atualizador de pacotes
          pip install -r requirements.txt # Instalando as biblioteas
          python3 app.py # Executando a aplicação
    
